name: Main workflow

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade -r requirements.txt pytest python3-memcached flake8 isort

    - name: Run isort
      run: isort --check-only --diff --recursive rmoq

    - name: Run flake8
      run: flake8

    - name: Run tests
      run: pytest

    - name: Python Semantic Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_TOKEN }}
